[phases.setup]
nixPkgs = ["chromium", "nodejs_20", "xvfb", "dbus", "glibcLocales"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["echo 'Build complete'"]

# تشغيل التطبيق داخل جلسة D-Bus خاصة
[start]
cmd = "dbus-run-session -- xvfb-run -a --server-args='-screen 0 1920x1080x24' node index.js"

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/nix/var/nix/profiles/default/bin/chromium"
